### ISSUE TITLE
EPIC: migrate solvis-graphql-api features 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis#30]
some features were developed in **solvis-graphql-api**  can made  be more widely available and more generalised in **solvis** 

Considering:
 - site-rupture radius calculations (runtime vs stored)
 - do we want a separate library for visualisation features (e.g. color scales), 

Done when:
 - [x] #37
     - fault and rupture distance filtering
     - parent fault filtering
     - [x] #42 

Future Candidates: 
 - [x] get fault surfaces geojson
 - [x] get fault traces geojson
 - [ ] geojson styling helpers
 - [ ] color scale
