### ISSUE TITLE
Epic Feature: enhanced participation rate options

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis#42]
ref (https://github.com/GNS-Science/solvis-graphql-api/issues/46#issue-2286634984)
and https://github.com/GNS-Science/kororaa/issues/455

Our support for participation rate can be improved/formalisedrounded so that the various use cases for this concept are all supported, clearly defined and named well.

> We want to be able to filter for fault participation rate. This is the combined rate for all subsections on that "parent" fault (i.e. the highest cumulative MFD rate for all subsections of the fault)`

### Overview 

There are 3) levels where we want to calculate and use Participation Rate values:
 1. at the **subsection** level
 2. at the **fault** level (aka ParentFault) level 
 3. at the **named-fault**  level - where named faults is a mapping from each **fault** (by name) to a parent **named-fault**
    **NB** this one needs the mapping data, which is not included in the NSHM_1.* inversion solutions. 
 
And, there are two options when calculating rates:  
 - A. the participation rate including all ruptures within the solution (i.e. the entire fault system )
      **NB** this option may be used as a [filter criteria itself](https://github.com/GNS-Science/kororaa/issues/455)
 - B. the participation rate for a given set up ruptures - where the user had narrowed these down using some criteria. eg. i) just those ruptures intersecting  a given a polygon, or ii) ruptures exceeding some magnitude, or iii) involving some particular fault. 

see discussion in https://github.com/GNS-Science/solvis-graphql-api/issues/59 where B is called the "Conditional Participation Rate" and A) the "Participation Rate"

## Done Criteria

  - provide a dataframe series/function for each permutation of the discussion above:
      - [x] subsection_participation_rate
      - [x] fault_participation_rate
      - [x] subsection_conditional_participation_rate
      - [x] fault_conditional_participation_rate
 - [x] update solvis documentation to explain all this
 - [x] use caching where applicable to maximise performance

**split out to new tickets** 
 
 - #47
 - #49
 - #50
 - #51
 - #52

### Related tickets:

 * https://github.com/GNS-Science/kororaa/issues/455
 * https://github.com/GNS-Science/solvis-graphql-api/issues/46
 * https://github.com/GNS-Science/solvis-graphql-api/issues/59
 * https://github.com/GNS-Science/solvis/issues/30
 * https://github.com/GNS-Science/solvis-graphql-api/issues/31 which is dependent on the participation rate

**Comment by chrisbc** [comment]
## NamedFaults

The Rupture Set `RmlsZToxMDAwODc=` is used in all NSHM_V1.0.* Inversion Solutions. This rupture set used the 
fault_model: `CFM_1_0A_DOM_SANSTVZ`

and it looks like this is defined here: https://github.com/GNS-Science/nzshm-opensha/blob/main/src/main/resources/faultModels/cfm_1_0A_no_tvz.xml.FaultsByNameAlt.txt

**TODO:** 

 - [ ] check that all the fault names in current NSHM model align wiht this mapping, and then ...
 - [ ] include this mapping in solvis (as a workaround to support the historic solutions)
 - [ ] ask for the mapping to be included in future opensha solutions

**Comment by chrisbc** [comment]
closed by #67
