### ISSUE TITLE
Solvis EPIC: Composite Inversion Solution

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/solvis#9]
We want to work with a complete NZSHM model version as if it's a single inversion solution, so that user can:
 - [x] get rates for all ruptures in the model
 - [x] visualise the fault surfaces
 - [x] visualise the rupture surfaces
 - [x] see what Inversions Source(s) a given rupture links to
 - [x] get aggregated rate info for each unique rupture (although the rupture is unique, the IS rates will vary)
 - [x] location proximity filtering
 - [x] rate filtering
 - [x] magnitude filtering

Key things to handle:
 - [x] #10
 - [x] #11
 - [ ] #12
 - possible case where same rupture geometry has different rupture set sources (not an issue now)
